[tool.poetry]
name = "tsp"
version = "0.1.0"
description = "tsp"
authors = ["tsp <tsp@example.com>"]
package = [
    {include = "harness_reward_model_ranking_collection"}
]



[tool.poetry.dependencies]
python = "^3.8"
transformers = "^4.11.3"
torch = "^1.10.0"
tqdm = "^4.62.3"

